version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      -  3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fastapi_blog
      - MYSQL_PASSWORD=admin